### ISSUE TITLE
Add tool to automate rke2-charts update

### ISSUE THREAD

**Issue by jossemargt-3pillar** [rancher/ecm-distro-tools#12]
### Background

The rke2-charts are downstream updated each time a Kubernetes component or Kubernetes itself. The big picture desire has been documented on [rke2#2077](https://github.com/rancher/rke2/issues/2077), this tool is part of it.

### Request

Create a Go tool that updates the rke2 referenced versions within the existing rke2-charts. A version reference can be:

- Package version
- Helm chart version
- Helm chart appVersion
- Docker image tag within values.yaml file

### Acceptance criteria

- Working Go tool on ecm-distro-tools able to perform the behavior described above.

**Comment by briandowns** [comment]
We have a number of different wants of updating charts, by a couple different groups, with additional inconsistencies leading to unnecessary and tough to manage complexity. Closing for now. Will readdress if any of the aforementioned issues changes.
