### ISSUE TITLE
Use previous merged date to find pull requests for release notes

### ISSUE THREAD

**Issue by matttrach** [rancher/ecm-distro-tools#131]
After reading the code for finding release notes I thought it would be cool to have a way to manually validate the release notes "changes since" section.
The code uses the compare API, so it was a bit more complex than I wanted to take on for manual verification, and I found a small issue query which finds the same information:

https://github.com/rancher/rke2/issues?q=base%3Arelease-1.23+merged%3A%3E2022-06-13+sort%3Aupdated-asc+
`base:release-1.23 merged:>2022-06-13 sort:updated-asc`

This may be slightly less accurate since it pulls PRs based on date rather than PRs for commits which merged between tags, but so far I have not found any practical cases where it has not matched up. This is a much easier to parse and limits the queries to a single call to GH vs the O(n) that the code currently operates on (it gets all commits, then queries every commit for a PR, then dedups the PR list ).  It is not much of a practical improvement, since we don't really have thousands of commits to parse, but it does help conceptually with understanding what we are looking for and provides an easy way to manually validate, which helps with the learning/training process. It also reduces calls to the GH API, which does get rate limited after a certain number of queries.

You need two pieces of information, the target branch and the previous release date. I also sorted by last updated to get the same sorting as the current code. The failure mode for this is if someone merges a PR for the next release on the day the release is cut you might miss that PR in the release notes.

**Comment by briandowns** [comment]
This isn't necessary at this time but can be reopened if it becomes so.
