### ISSUE TITLE
Reconfigure s390x Builds to not fail silently

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#155]
First step is to perform an audit on which repos are configured for s390x to fail silently. This list should put put in here as a comment. From there, we'll divide up the work to remediate all offending repos.

**Comment by nikolaishields** [comment]
[ ] test

**Comment by matttrach** [comment]
Configured to fail silently:
https://github.com/rancher/rke2/blob/release-1.23/.drone.yml
https://github.com/rancher/rke2/blob/release-1.22/.drone.yml

Not Configured to fail silently:
https://github.com/rancher/rke2/blob/release-1.24/.drone.yml
https://github.com/rancher/rke2/blob/master/.drone.yml

**Comment by matttrach** [comment]
rancher/image-build-base:
- s390x was not ignored when it was originally added
- https://github.com/rancher/image-build-base/commit/57267e142bcec901102fb5e709132b6e2cd4b5be#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7

**Comment by matttrach** [comment]
rancher/rke2:
- s390x was ignored when originally added
- s390x ignore commands were removed in a later commit that was only added to v1.24 and v1.25
- https://github.com/rancher/rke2/commit/7b3080b65cbb2ba091fec166ccde836ad456ca33
- https://github.com/rancher/rke2/blob/9b54ea192063da19cb488312b6ff5a23b088b2bb/.drone.yml
