### ISSUE TITLE
Update release asset counts

### ISSUE THREAD

**Issue by brooksn** [rancher/ecm-distro-tools#157]
- Check that each value in verify_release_assets is correct. 
- Handle cases where different versions have different expected asset counts in the same repo

**Comment by caroline-suse-rancher** [comment]
@brooksn Can you come back and update this ticket with new requirements?

**Comment by brooksn** [comment]
Since v1.24.3+k3s1, the expected asset count is 23 (including source code), and all of the current release branches share the same expected count. Also, bin/verify_release_assets should be removed, and only release.go should be updated. https://github.com/rancher/ecm-distro-tools/blob/master/release/release.go#L183
