### ISSUE TITLE
SSH operations within k3s_release need to be updated to reflect Github standards

### ISSUE THREAD

**Issue by nikolaishields** [rancher/ecm-distro-tools#162]
Presently the k3s_release utility makes the following assumptions that should be generalized:
- keys are stored in the `~/ssh`
- the key is named (~/.ssh/id_rsa)
- The key is an 2048b RSA key with SHA-1, with the resulting error message
```
FATA[0001] failed to clone and setup remotes for k8s repo: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type. 
```
### Potential Fixes
- Avoid using ssh altogether by using the github token available within the tools existing configuration.
- By using the ssh-agent within the environment or variabalizing the key name could allow users to specify the key to be used within the tools configuration.
- Add a flag to specify the users key

https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/

**Comment by briandowns** [comment]
I think the 3rd option is most reasonable of the lot. Per the poll, the majority of users aren't using an agent and we want to be careful with how much basic git operation we abstract away from git and subsequently couple with the overaching management system.

**Comment by nikolaishields** [comment]
After digging into this issue and the go-git library I've found that we have no need to support git ops via ssh auth. The library supports the use of token based auth (https://pkg.go.dev/github.com/go-git/go-git/v5#example-PlainClone-AccessToken). In the short term this also improves opdoms functionality by not shouldering the burden of key-management on the users behalf.

```go
// Tempdir to clone the repository
dir, err := ioutil.TempDir("", "clone-example")
if err != nil {
	log.Fatal(err)
}

defer os.RemoveAll(dir) // clean up

// Clones the repository into the given dir, just as a normal git clone does
_, err = git.PlainClone(dir, false, &git.CloneOptions{
	URL: "https://github.com/git-fixtures/basic.git",
	Auth: &http.BasicAuth{
		Username: "abc123", // anything except an empty string
		Password: "github_access_token",
	},
})

if err != nil {
	log.Fatal(err)
}```

**Comment by briandowns** [comment]
Not needed at this point.
