### ISSUE TITLE
The build container within k3s_release uses the wrong alpine version

### ISSUE THREAD

**Issue by nikolaishields** [rancher/ecm-distro-tools#165]
The k3s_release presently makes the assumption for the alpine containers semver to be used in conjunction with the insertion of the go version. This is brittle and prone to breaking unpredictably due in part to the Alpine maintainers exclusively fixing forward and not back-porting alpine version to previous go versions.

### Potential Fixes
-  Query dockerhub for the available go images and use the latest image corresponding to the supplied go version (see the example request below)
`curl -s -H "Accept: application/json" -X GET https://hub.docker.com/v2/repositories/library/golang/tags/\?page\=1\&name=1.19.4 | jq  -r '.results[].name|match("^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-alpine)(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"; "gm").string'`
- Remove the build container and rely on relevant build-base images in circulation within the rancher ecosystem.

**Comment by briandowns** [comment]
Completed via #167
