### ISSUE TITLE
Token scopes should be used within the k3s_release utility to stay update with Github

### ISSUE THREAD

**Issue by nikolaishields** [rancher/ecm-distro-tools#166]
The k3s_release release utility relies on legacy GitHub tokens with global scopes. We could improve this by making use of the new token scopes to limit that permissions users supply to k3s_release and by extension, opdom in the future.

**Comment by brooksn** [comment]
I was able to use a new fine-grained personal access token (I think only modify-k3s subcommand uses it).
<img width="398" alt="Screenshot 2023-01-13 at 10 00 26 AM" src="https://user-images.githubusercontent.com/5132558/212389226-4215d9cd-b2ae-475e-af56-5b835567380e.png">

**Comment by galal-hussein** [comment]
@brooksn yeah looks like we just need to set the right permissions to the PAT, I tested with the right permissions and was able to create a normal pull request with the created client https://github.com/galal-hussein/k3s/pull/29
