### ISSUE TITLE
Investigate the use of .droneignore.yml for relevant repos

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#170]
Drone supports the ability to ignore certain changes in specified files in a `.droneignore.yml` file.

**Comment by nikolaishields** [comment]
It initially appears that the drone ignore capabilities are supplied via the extension system:
https://github.com/meltwater/drone-convert-pathschanged

The above extension grants us the ability to include/exclude pipeline steps based on file and path changes. In some ways this is similiar the Nx and Bazel monorepo builds tools. To achieve the goal of ignoring full CI runs when updating the channels server we could append the following logic to each architecture pipeline.

```yaml
  when:
    paths:
      exclude:
      - channel.yml
```
It might be beneficial to consider what other edge case conditions we'd like to limit runs for while drafting a change of this nature.

**Comment by matttrach** [comment]
The [k3s PR](https://github.com/k3s-io/k3s/pull/6996) has been approved, just waiting for repo to thaw

**Comment by matttrach** [comment]
It is important to stakeholders that this is a step to be more judicious about what we dedicate resources to for e2e tests rather than just a way to skip files we think are not important.

**Comment by matttrach** [comment]
It is important to remember that this only effects tests provided by drone, not all CI, we are adding more and more tests to GH actions. This gives us the ability to choose when not to run drone tests based on the files in the PR, which may be picked up by GH actions.
