### ISSUE TITLE
Automate the creation of PRs updating image-build-base when image-build-base releases

### ISSUE THREAD

**Issue by manuelbuil** [rancher/ecm-distro-tools#18]
When image-build-base releases a new version, all the rancher/image-build-xxxx projects [1] should update their Dockerfiles. We are talking about ~24 projects. This process is not automated but manual and the consequence is that most of them are outdated.

It'd be so great that a PR would be created for each of them updating that parameter (e.g https://github.com/rancher/image-build-calico/blob/master/Dockerfile#L4) every time there is a new release of image-build-base.

Ideally, we should trigger this from drone/github_actions/etc in the image-build-base github project as soon as there is a new release. However, as we are still unsure what will be our CI at the end of the year, I think it would be great to start having the functionality here.

[1] https://github.com/orgs/rancher/repositories?language=&q=image-build-&sort=&type=all

**Comment by briandowns** [comment]
Check out https://github.com/rancher/ecm-distro-tools/blob/master/bin/update_go

**Comment by manuelbuil** [comment]
> Check out https://github.com/rancher/ecm-distro-tools/blob/master/bin/update_go

Nice! I did not know this :). Closing!
