### ISSUE TITLE
Create Calculator in Go using C Code

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#207]
Create a calculator in C code. This should be a simple group of functions with the following signatures:

```c
static double
addition(const double x, const double y);

static double
subtract(const double x, const double y);

static double
multiply(const double x, const double y);

static double
divide(const double x, const double y);
```

Create a calculator in Go but the function implementations should call the C code implementations.

No CLI implementation is necessary.

**Comment by Tashima42** [comment]
https://github.com/Tashima42/cgo-calculator

**Comment by briandowns** [comment]
Completed.
