### ISSUE TITLE
gen_release_notes double asterisks

### ISSUE THREAD

**Issue by brooksn** [rancher/ecm-distro-tools#219]
A doubly-nested list was rendered under the issue titled "E2E Backports" when running this gen_release_notes command:
```sh
gen_release_notes -p v1.24.14+k3s1 -m v1.24.15-rc1+k3s1 -r k3s
```

**Comment by Tashima42** [comment]
The `User-Facing Change` field for [this PR](https://github.com/k3s-io/k3s/pull/7726) already had asterisks. 

A solution would be to add `strings.Replace(releaseNote, "* ", "", -1)` or something like this. 
Another solution would be to not add asterisks to that field and don't add an edge case to the code. I think it depends on how common this is, I'll take a better look at the previous release notes and come back with some more info.

**Comment by brandond** [comment]
We could probably also look at fixing this with some standards around what we put in the release notes field on the PR.

**Comment by Tashima42** [comment]
That is a great idea @brandond, I suggest adding some instructions to the PR template, like "always start the User-Facing Change with letters and separate changes by lines".

**Comment by Tashima42** [comment]
I submitted a PR to K3s with my suggestions: https://github.com/k3s-io/k3s/pull/7878
To keep it as simple as possible, I included only what I judged as necessary for `gen_release_notes` to work properly

**Comment by brandond** [comment]
Thanks, I commented with some suggestions.

RKE2 is currently missing this section from the PR template, would you mind opening a PR to add it, with the same content as we settle on for K3s?

**Comment by caroline-suse-rancher** [comment]
@briandowns Can you advise on follow-on work for this since the initial PR was closed?

**Comment by caroline-suse-rancher** [comment]
@Tashima42 it sounds like we need to verify if the double asterisk is still an issue and fix if it is
