### ISSUE TITLE
Update KDM CI to include validation for featureVersions.encryptedKeyRotation

### ISSUE THREAD

**Issue by rancher-max** [rancher/ecm-distro-tools#244]
The goal here is to ensure that we include this argument when making PRs against KDM. The argument was initially defined here: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.8/channels.yaml#L185-L186 and here: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.8/channels-rke2.yaml#L431-L432
and should be present for every release after those in both k3s and rke2. 

I am not 100% sure what is happening in the drone CI today, but I think it's probably easiest if it uses a similar approach to how the chart versions are checked and just ensures that the key for `featureVersions.encryptedKeyRotation` is present. I don't necessarily care about the value on that key.

**Comment by Tashima42** [comment]
I fixed the first round of reviews, ready for another one.
