### ISSUE TITLE
Ability to post status of drone build in slack channel for tagging releases

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#245]
Currently, after we tagging a release in rancher/rancher, it's monitored and then announced updates by a human.

Can we post the status of drone build when all steps succeed in Drone? 

Slack channel to pos statust: #team-rancher-release-coordination

**Comment by cwayne18** [comment]
Note that we /may/ need to go through worker's council to enable a slack app, maybe we can sneak in with a webhook or something instead

**Comment by briandowns** [comment]
This is a prime job for OpDom.

**Comment by luisrojas2** [comment]
Below configuration about publishing the drone's pipeline status in slack
**Configuration:**

**Slack**
*Note*: It needs to be done by the SUSE slack workspace admin. [Link](https://api.slack.com/messaging/webhooks)

    1. Create a slack app [link](https://api.slack.com/apps)
      - Click the "create new app" button
      In the dialog box:
      - Enter App name as desired, E.G. "NotificationApp"
      - Select "Suse workspace" option
      - Click the "Create app" button
      Once the app is created, at settings > basic information > Install your app:
      - Click the "Install to workspace" option
      - Choose channel: "team-rancher-release-coordination"
      - Click the "allow" button to grant permissions
      The app must be created successfully in the workspace and in the appropriate channel.
      
    2. Create incoming Webhooks
      In the settings of created application, from left menu panel:
      - Select "Incoming webhooks" option
      - Scroll down and click "Add new webhook to workspace" button
      - Select the channel: "team-rancher-release-coordination"
      - Click the "allow" button to grant permissions
      The Webhook Url must be created
      - Copy and save it content.

**Drone IO**
*Note*: It needs to be done by admin user.

    * In the  rancher repository of drone IO [link](https://drone-publish.rancher.io/rancher/rancher), steps:
      - Click the "settings" option from panel
      - Click the "Secrets" option
      - Click the "New secret" button on the right side
      In the dialog box:
      - Add the secret name, E.G. "slack_webhook" (variable name replaced in the GH .drone pipeline)
      - Add the value from the "Webhook url" generated in the last step of slack configuration
      - Click the "create" button
      The secret webhook url must be configured.

**Github**
*Note*: Once the above configuration is done, a GH PR can be created with folowwing information:

    * In the rancher/rancher GH repository:[link](https://github.com/rancher/rancher/blob/release/v2.8/.drone.yml)
     - Modify the ".drone.yml" file
     - Add the notification plugin/slack step to the pipeline yaml, [example](https://github.com/luisrojas2/drone-quickstart/blob/main/slack-plugin-step.yml)
     - Save the ".drone.yaml" file 
     - Create the PR in order to apply changes to main branch

Notification should look like below:

![tag-notification](https://github.com/rancher/ecm-distro-tools/assets/109705631/5c3c819a-0699-4086-88d5-1275ba25c7d8)

**Comment by briandowns** [comment]
@luisrojas2 Can you add an issue to github.com/rancherlabs/eio and request what's needed for this to be completed? Please add a link to this issue so they know exactly what we're try to achieve as well as tag myself, Denise, and Chris.
