### ISSUE TITLE
Automate tagging the latest GA release of rancher/rancher to also be the latest tag for rancher/rancher

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#247]
This one might be a bit more complex as we publish a lot of different release lines, but we manually have to update the latest docker image for rancher/rancher to the latest version of Rancher. 

This doesn't have to be in drone step but could be based on a GH action or some other tool, but not having to manually run a script.

**Comment by brooksn** [comment]
Related to #273, which adds the semv cmd. Next step after merging #273 is a pull request into rancher/rancher to add a GitHub workflow that promotes the docker `latest` tag when a release is published or edited.
