### ISSUE TITLE
Create a way to automate being able to set the dev or production branch for all Chart references

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#252]
Current Manual Process:

Create a PR that moves from development branches to production branches for charts and system-charts.

**Update variables in settings/settings.go** 

- [ChartDefaultBranch](https://github.com/rancher/rancher/blob/release/v2.8/pkg/settings/setting.go#L117) - Branch where charts are pointed to 

**Update variables in scripts/package-env** - Used to properly generate the rancher-images.txt and rancher-image-sources.txt that are release artifacts 
- [SYSTEM_CHART_DEFAULT_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/scripts/package-env#L5) - Branch where system-charts are pointed to 
- [CHART_DEFAULT_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/scripts/package-env#L7) - Branch where charts are pointed to

**Update arguments in package/Dockerfile** 
- [SYSTEM_CHART_DEFAULT_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/package/Dockerfile#L19) - Branch where system-charts are pointed to
- [CHART_DEFAULT_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/package/Dockerfile#L20) - Branch where charts are pointed to

**Comment by Tashima42** [comment]
Update the command to identify the directory and current branch instead of using flags.

The user will go to the local rancher repo, switch to the base branch and will not need to set the current set kdm branch, the command needs to automatically identify these infos.
```bash
rancher_release-darwin-arm64 set-kdm-branch-refs --new-kdm-branch DEMO --create-pr
```
