### ISSUE TITLE
Ability to run a GH action or some automation step to list out which images are still in RC form when a tag is created 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#254]
Currently, the manual step after the final RC (the RC with no RC images) is to:

Review the images.txt artifacts that there are no images with a tag containing -rc. Announce in #team-release-coordination which images still have RC tags. 

Navigate to the GitHub tags page
Navigate to the latest RC page
Download the primary images.txt file
Find any non-mirrored image tags have a suffix with the following format: "-rcX"

**Comment by briandowns** [comment]
* Subcommand in CLI
* Templated output for Slack

**Comment by Tashima42** [comment]
Update to be able to run this check with just a branch, instead of having to tag an RC.

**Comment by deniseschannon** [comment]
We may want to investigate this issue instead: https://github.com/rancher/ecm-distro-tools/issues/291

**Comment by tashima42** [comment]
Won't be implemented anymore
