### ISSUE TITLE
Ability to apply GH labels to issues and comment on them after a RC is available

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#255]
The following actions occur after a RC is available:

Update any issues with the label  "[zube]: Waiting for RC" tickets to "[zube]: To Test".
Under every issue moved, comment which RC they are available for testing on (e.g. "Available to test on v2.6.1-rc3")

**Comment by briandowns** [comment]
This can be a subcommand in the CLI. Will need more investigation.
