### ISSUE TITLE
After a Rancher Manager RC, ability to apply labels to issues to move to test and comment which RC it's available in

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#257]
Current manual steps that occur after each RC:

**Move any issues needing an alpha/RC tag to test and comment which version:**

Update any issues with the label  "[zube]: Waiting for RC" tickets to "[zube]: To Test".
Under every issue moved, comment which RC they are available for testing on (e.g. "Available to test on v2.6.1-rc3")

**Comment by briandowns** [comment]
This isn't that dissimilar to #255 and the work is likely to overlap significantly enough to lump into the same effort.
