### ISSUE TITLE
Investigate Branch Protection Automation

### ISSUE THREAD

**Issue by briandowns** [rancher/ecm-distro-tools#266]
We need to investigate a means of how we can automate providing branch protection in GitHub for various branches and repositories. 

How can we set these protections aside from the UI?

What are the criteria we can set for protection? Ie date, version (current tag), label, etc.

Can we assign certain users or groups to be able to still merge when protected?

Can we assign certain users to be able to unfreeze the branches, at the time we set the protection? Ie captains.

**Comment by deniseschannon** [comment]
When looking into protection, is there a way to allow for fixes for tests (CI or validation) be allowed in?

**Comment by Jono-SUSE-Rancher** [comment]
There are a lot of great ideas in a separate thread that I want to try and collect into this ticket, so here goes.

**From @jakefhyde **

- Add CODEOWNERS to all repos
- Enable some more aggressive linting (potentially for net new code,
- Don't run tests for every PR until it is marked as ready to test (we run out of s390x runners often)
- Only select a subset of unit/integration/e2e tests to run on PR (default to P0 test cases)
- Add a github action to ensure codecoverage doesn't go down (below a percentage?) per test
- Optionally, add an action that ensure all net new code is tested and has godoc comments
- Add a github action to freeze repositories
- During freeze, lock down all repos to first mates, backup first mates, and admins
- Specifically lock down Dockerfiles, Dockerfile.dapper, and go.mod, as well as KDM+charts
- Add a github action to thaw repositories
- Branch and tag protection (both during freeze and thaw)
- Let other repos run rancher (and potentially other repos) e2e tests before they are merged/released
- Github action to ensure all repos are released and vendored in to appropriate repos for a given release

----

**From @pjbgf **
We could create a simple GitHub action which checks a central location (given repository within the org) that keeps the centralised list of repositories and branches that are currently in code freeze. Adding that GH Action across all repositories, combined with the built-in Require status checks to pass before merging could be a way to automate this.

----

**From @MbolotSuse **
As far a solutions go, I would say that the most simple approach would be to use a [codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file that restricts merging to first-mates and the release captain (I believe there is already a github group for this). This file can be updated with that requirement once we have reached code-freeze, and the file can be changed to allow merging to the dev teams again after release has occurred.
I would say communicating the code-freeze state in [#team-rancher-release-coordination](https://suse.slack.com/archives/C02CNGX1XFH) is good enough if we have a technical protection that prevents merging.

----

**Comment by Tashima42** [comment]
Answers to questions on protected branches:

1. Would it be possible to turn on and off branch protection using the GitHub API?
   * Yes, it is possible to turn on, off and configure branch protection via the GitHub API: [REST](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection), [GraphQL](https://docs.github.com/en/graphql/reference/input-objects#createbranchprotectionruleinput)
2. What permissions are required to do so?
    * "People with admin permissions or a custom role with the "edit repository rules" permission to a repository can manage branch protection rules." [DOCS](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)
3. Can we assign different users to have the ability to turn it on and off?
    * Yes, if they have the "edit repository rules" permission
4. Can we whitelist certain users who can merge while a branch is frozen?
    * Yes: By default, the restrictions of a branch protection rule don't apply to people with admin permissions to the repository or custom roles with the "bypass branch protections" permission. You can optionally apply the restrictions to administrators and roles with the "bypass branch protections" permission, too. [DOCS](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)
    * Also, it is possible to restrict who can push to a branch, users, teams and apps: [DOCS](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#restrict-who-can-push-to-matching-branches)
5. Can we control branch protection based on file type?
    * Not with branch protection rules.
6. Is there a way to allow for fixes for tests (CI or validation) be allowed in?
    * Yes, if they are merged by someone with permission to do so.

**Comment by Tashima42** [comment]
Possible solutions for code freeze: 

1. Suggested by @pjbgf: Central location with code freeze information for repos and a Github Action that applies those rules.
    - Use the Github API in a command in `ecm-distro-tools` to fetch and apply rules
    - To bypass code freeze, either require the central location to be updated or allow admins to bypass branch protections

2. Use a tool like https://github.com/marketplace/merge-freeze to define and apply rules.

3. Write our own Github App that controls code freeze and host it.

**Comment by tashima42** [comment]
Closing as stale
