### ISSUE TITLE
Review/update shell script of checking RC images

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#291]
There is a script that reviews what is in RC in a Rancher release:

https://github.com/rancher/rancher/blob/release/v2.8/scripts/create-components-file.sh

rancher-images.txt
rancher-windows-images.txt
Dockerfile
go.mod

My bash skills aren't great, but does it check pkg/apis/go.mod pkg/settings/settings.go?

Is it possible to list out for each component, what file the RC info is still listed? 

<p><br /></p><p><a href="https://github.com/rancher/rancher/blob/release/v2.8/Dockerfile.dapper">https://github.com/rancher/rancher/blob/release/v2.8/Dockerfile.dapper</a><br /><a href="https://github.com/rancher/rancher/blob/release/v2.8/package/Dockerfile">https://github.com/rancher/rancher/blob/release/v2.8/package/Dockerfile</a><br /><a href="https://github.com/rancher/rancher/blob/release/v2.8/pkg/settings/setting.go">https://github.com/rancher/rancher/blob/release/v2.8/pkg/settings/setting.go</a><br /><a href="https://github.com/rancher/rancher/blob/release/v2.8/go.mod">https://github.com/rancher/rancher/blob/release/v2.8/go.mod</a><br /><a href="https://github.com/rancher/rancher/blob/release/v2.8/pkg/apis/go.mod">https://github.com/rancher/rancher/blob/release/v2.8/pkg/apis/go.mod</a><br /><a href="https://github.com/rancher/rancher/blob/release/v2.8/scripts/package-env">https://github.com/rancher/rancher/blob/release/v2.8/scripts/package-env</a></p>
# Helpful command to use in the root of rancher/rancher repo for the modules dependencies grep "\-rc" go.mod pkg/apis/go.mod package/Dockerfile Dockerfile.dapper pkg/settings/setting.go scripts/package-env
--

<p class="auto-cursor-target"><br /></p>

**Comment by briandowns** [comment]
Templatize the output to be similar to how the rancher/rancher script is outputing the info for the update to the release in GH.

**Comment by deniseschannon** [comment]
Script Update:

* Remove references of `dev` in the Components with -rc section
* Split Components with dev- section into 2 new sections
  * KDM References with dev branch
  * Chart References with dev branch

Script to be updated in release/v2.8, release/v2.7 and create a GH action for it.

**Comment by deniseschannon** [comment]
This looks good. Let's update release/v2.8 so that it could be part of the next tagging of the RC.

**Comment by deniseschannon** [comment]
When updating rancher/rancher for the script, we want to updated it in both `release/v2.8`, `release/v2.7`, `release/v2.6` branches. 

https://github.com/rancher/rancher/blob/release/v2.8/scripts/create-components-file.sh
https://github.com/rancher/rancher/blob/release/v2.7/scripts/create-components-file.sh
https://github.com/rancher/rancher/blob/release/v2.6/scripts/create-components-file.sh
