### ISSUE TITLE
backport tool can't find issue

### ISSUE THREAD

**Issue by manuelbuil** [rancher/ecm-distro-tools#317]
I downloaded the tools with `./install.sh v0.27.0` and then I was trying to backport my PR to three branches by using the command:
```
/home/manuel/.local/bin/ecm-distro-tools/backport -r k3s -b "release-1.27,release-1.26,release-1.25" -i 8911 -c c91d6a5099d940a72a76cdc0a51b779964033edb
```
But I got the following output:
```
GET https://api.github.com/repos//k3s/issues/8911: 404 Not Found []
```
But the issue exists ==> https://github.com/k3s-io/k3s/issues/8911

**Comment by manuelbuil** [comment]
Tried with rke2 and same problem: `/home/manuel/.local/bin/ecm-distro-tools/backport -r rke2 -b "release-1.28,release-1.27,release-1.26" -i 5156 -c 46e43ade786c76c3e814db6f4ff2eea8cf507ca1`

**Comment by Tashima42** [comment]
Hi, @manuelbuil I did some testing, and it looks like the flat `-o` for `owner` is missing in the help message. If you add this, it should work fine.

```
/home/manuel/.local/bin/ecm-distro-tools/backport -r rke2 -o rancher -b "release-1.28,release-1.27,release-1.26" -i 5156 -c 46e43ade786c76c3e814db6f4ff2eea8cf507ca1
```

We're doing a new release soon that fixes this issue. I'll keep you informed.
