### ISSUE TITLE
Implement check of integrity between rancher/charts/index.yaml && charts.rancher.io/index.yaml 

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/ecm-distro-tools#475]
We serve charts in 3 ways: 
- https://github.com/rancher/charts `Github Repo`
- https://git.rancher.io/charts `Main mirror`
- charts.rancher.io `Alternative`

Whenever we release charts on a specific branch (e.g., `2.8`), they are all updated at the same time. 
When a new branch is added (e.g., `2.9`), a one-time-only process is required. The time between this process's execution takes many months. It is easy to forget, and sometimes, it has to be executed twice.

For reference: https://github.com/rancher/charts/pull/2220 

## Task 
Implement a GH Action job that will check the integrity of the `charts.rancher.io/index.yaml file` and the `https://github.com/rancher/charts/index.yaml file`. 

`caveats`:
The `charts.rancher.io/index.yaml file` is always based on the latest active branch. 
i.e: 
We currently have 3 active branches: `2.7`; `2.8`; `2.9`
The `charts.rancher.io/index.yaml file` must be up-to-date with `2.9` only.

When a new active branch is released for the first time the same rule will apply to it.

**Comment by recena** [comment]
What about the Partner Helm Chart Catalog?

**Comment by nicholasSUSE** [comment]
> What about the Partner Helm Chart Catalog?

@recena 

I don't know the process for the `partner charts`. 
This is only needed on the `charts` side because we always have 3 active release branches that are ever-changing. 

If I am not mistaken, there is only 1 active release branch on `partner-charts`, so you should never have this problem.

**Comment by nicholasSUSE** [comment]
Charts-build-scripts implementation PR:
https://github.com/rancher/charts-build-scripts/pull/150

**Comment by nicholasSUSE** [comment]
Tested workflows:
- https://github.com/rancher/charts/actions/runs/10857566785/job/30134186368
- https://github.com/rancher/charts/actions/runs/10857193315/job/30133223833?pr=4441

Final adjustment pr on charts:
- https://github.com/rancher/charts/pull/4440
